matrix:
  include:
    # Smart contract tests
    - language: node_js
      node: 8
      services:
        - trufflesuite/ganache-cli
      install:
        - npm install -g truffle ganache-cli
        - npm install 
      script: 
        - npm run ganache
        - sleep 5
        - truffle migrate --network development
        - npm run test/truffle 
        
    # Front end tests
    - language: node_js
      node_js: 8
      before_script:
        - npm install 
      script:
        # Fix tests later 
        - npm run test 
 
   # Documentation
   - language: node_js
      node: 8
      install:
        - npm install -g @doxity
        - npm install 
      script:
        - doxity build