matrix:
  include:
    # Smart contract tests
    - language: node_js
      node_js:
        - "7"
        - "8"
        - "9"
        - "tip"        
      before_script:
        - npm install -g truffle ganache-cli
        - npm install 
      script: 
        - npm run ganache
        - sleep 5
        - truffle migrate --network development
        - truffle test

    # Front end tests
    - language: node_js
      node_js: 
        - "8"
      before_script:
        - npm install 
      script:
        # Fix tests later 
        - npm run test 
       
   # Deploying
    - language: node_js
      node_js:
        - "7"      
        - "8"      
      before_script:
        - npm install -g doxity 
        - npm install 
      script: 
        - doxity build 