sudo: required
matrix:
  include:
    # Smart contract tests
    - language: node_js
      node:
        - "7"
        - "8"
        - "9"
        - "tip"        
      before_script:
        - npm install -g truffle ganache-cli
        - npm install 
      script: 
        - npm run ganache
        - sleep 5
        - truffle migrate --network development
        - truffle test

    # Front end tests
    - language: node_js
      node: 
        - "7"
        - "8"
        - "9"
      before_script:
        - npm install 
      script:
        # Fix tests later 
        - npm run test 
       
   # Deploying
    - language: node_js
      node_js:
        - "7"      
        - "8"      
      before_script:
        - npm install -g @digix/doxity
        - sudo add-apt-repository -y ppa:ethereum/ethereum
        - sudo apt-get update
        - sudo apt-get -y install solc
        - npm install 
      script: 
        - doxity build

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep-history: true
#  on:
#    branch: master