sudo: required
matrix:
  include:
    # Smart contract tests
    - language: node_js
      node_js:
        - "8"
      before_script:
        - npm install -g truffle ganache-cli
        - npm install 
      script: 
        - npm run ganache
        - sleep 5
        - truffle migrate --network development
        - truffle test

    # Front end tests
    - language: node_js
      node_js: 
        - "8"
      before_script:
        - npm install 
        - ./node_modules/truffle/build/cli.bundled.js compile
      script:
        # Fix tests later 
        - npm run test 
       
   # Deploying
    - language: node_js
      node_js:    
        - "8"      
      before_script:
        - npm install -g @digix/doxity gatsby
        - sudo add-apt-repository -y ppa:ethereum/ethereum
        - sudo apt-get update
        - sudo apt-get -y install solc
        - cd doxity 
        - npm install
        - cd ../
        # install the doxity dependencies
      script: 
        - mv docs olddocs
        - doxity compile
        - doxity publish
        - mv -v olddocs/* docs/
     
   # Python mk docs 
    -  language: python
       python:
         - "2.7"
         - "3.7"
       before_script:
         - pip install mkdocs
         - npm i -g @soldoc/soldoc
       script:
         - soldoc --in ./contracts --out ./docs/contracts
         - mkdocs build
         - mv -v docs/* site/
       deploy:
         provider: pages
         skip-cleanup: true
         local_dir: site
         github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
         keep-history: true
         on:
           branch: master