site_name: File Track IPFS Dapp
repo_url: https://github.com/FriendlyUser/file-track-Dapp
site_description: Documentation for my project
site_author: David Li
copyright: David Li 2018
nav:
  - 'Introduction': '/'
  - 'Contracts':
      - 'FileList': 'contracts/FileList.md'    
      - 'Migrations': 'contracts/Migrations.md'
      - 'Simple Storage': 'contracts/SimpleStorage.md'
      - 'Complex Storage': 'contracts/ComplexStorage.md'
      - 'Tutorial Token': 'contracts/TutorialToken.md'