linkPrefix = "/IPFS-Dapp"
name = "drizzle-box"
version = "1.0.0"
buildTime = 2018-09-22T18:45:15.574Z
target = "scripts/doxity"
src = "contracts/*"
dir = "pages/docs"
source = "https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/a4886b7a7a04c018ac04fed3125d7d4785e74bed.tar.gz"
out = "docs"

[interaction]